# -*- coding: utf-8 -*-
"""Overfitting, Underfitting, Balanced Fitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFFzad5xD9vyV6H0j7q298MQQB1kxoQC
"""

#Overfitting, Underfitting, Balanced Fitting

import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df=sns.load_dataset('diamonds')

df.head(3)

df=pd.get_dummies(df,columns=["cut","color","clarity"],drop_first=True)

df.head(3)

y=df['price']
x=df.drop("price",axis=1)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=16)

lm=LinearRegression()
model=lm.fit(x_train,y_train)

model.score(x_test,y_test)

"""Bu ikisi arasındaki fark ne kadar az ise o kadar uyumlu öğrenmiştir. Bunlar arasındaki fark ne kadar yüksekse o kadar Overfittingdir(Aşırı öğrenmiştir)."""

model.score(x_train,y_train)